### ISSUE TITLE
Getting IllegalStateException for clj-http 1.0.1 on clojure 1.7.0-alpha4

### ISSUE THREAD

**Issue by gfrivolt** [dakrone/clj-http#238]
clj-http is used by elastisch 2.1.0, I get the issue below. When the application starts I get `WARNING: update already refers to: #'clojure.core/update in namespace: clj-http.client, being replaced by: #'clj-http.client/update`, this should have been resolved as I know in version 1.0.1. Why does it show up? Thank you for your help.

```
Exception in thread "async-dispatch-47" java.lang.IllegalStateException: Attempting to call unbound fn: #'clj-http.client/update
        at clojure.lang.Var$Unbound.throwArity(Var.java:43)
        at clojure.lang.AFn.invoke(AFn.java:48)
        at clj_http.client$wrap_decompression$fn__10653.invoke(client.clj:268)
        at clj_http.client$wrap_input_coercion$fn__10711.invoke(client.clj:391)
        at clj_http.client$wrap_additional_header_parsing$fn__10732.invoke(client.clj:462)
        at clj_http.client$wrap_output_coercion$fn__10702.invoke(client.clj:366)
        at clj_http.client$wrap_exceptions$fn__10611.invoke(client.clj:149)
        at clj_http.client$wrap_accept$fn__10742.invoke(client.clj:489)
        at clj_http.client$wrap_accept_encoding$fn__10748.invoke(client.clj:504)
        at clj_http.client$wrap_content_type$fn__10737.invoke(client.clj:480)
        at clj_http.client$wrap_form_params$fn__10788.invoke(client.clj:595)
        at clj_http.client$wrap_nested_params$fn__10806.invoke(client.clj:619)
        at clj_http.client$wrap_method$fn__10783.invoke(client.clj:578)
        at clj_http.cookies$wrap_cookies$fn__9392.invoke(cookies.clj:121)
        at clj_http.links$wrap_links$fn__10010.invoke(links.clj:50)
        at clj_http.client$wrap_unknown_host$fn__10814.invoke(client.clj:638)
        at clj_http.client$post.doInvoke(client.clj:753)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at clojurewerkz.elastisch.rest$post.invoke(rest.clj:43)
        at clojurewerkz.elastisch.rest.document$create.doInvoke(document.clj:55)
        at clojure.lang.RestFn.invoke(RestFn.java:470)
        at skrejp.storage.Storage.store(storage.clj:48)
        at skrejp.storage.Storage$fn__144$state_machine__6087__auto____145$fn__147.invoke(storage.clj:32)
        at skrejp.storage.Storage$fn__144$state_machine__6087__auto____145.invoke(storage.clj:27)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:940)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:944)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__6103.invoke(ioc_macros.clj:953)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__2571.invoke(channels.clj:102)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by xperian** [comment]
I am having this problem on Clojure  1.7.0-alpha5

**Comment by kul** [comment]
May be related to this
http://dev.clojure.org/jira/browse/CLJ-1604
