### ISSUE TITLE
why still use core_old.clj

### ISSUE THREAD

**Issue by chihyangscience** [dakrone/clj-http#286]
hi there,

I am now using [clj-http "2.0.0"], it works for me locally, but when I package my code into uberjar and deployed to jenkins, looks like it still use the core_old.clj namespace, do not know why:

22:53:58,346 ERROR [SoapUI] An error occurred [CONN_MANAGER_TIMEOUT], see error log for details
java.lang.NoSuchFieldError: CONN_MANAGER_TIMEOUT
	at clj_http.core$add_client_params_BANG_.invoke(core.clj:138)
	at clj_http.core$request.invoke(core.clj:239)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__3144.invoke(client.clj:796)
	at clj_http.headers$wrap_header_map$fn__1879.invoke(headers.clj:143)
	at clj_http.client$wrap_query_params$fn__3057.invoke(client.clj:624)
	at clj_http.client$wrap_basic_auth$fn__3064.invoke(client.clj:640)
	at clj_http.client$wrap_oauth$fn__3068.invoke(client.clj:650)
	at clj_http.client$wrap_user_info$fn__3073.invoke(client.clj:663)
	at clj_http.client$wrap_url$fn__3130.invoke(client.clj:762)
	at clj_http.client$wrap_redirects$fn__2885.invoke(client.clj:237)
	at clj_http.client$wrap_decompression$fn__2904.invoke(client.clj:309)
	at clj_http.client$wrap_input_coercion$fn__2996.invoke(client.clj:463)
	at clj_http.client$wrap_additional_header_parsing$fn__3017.invoke(client.clj:522)
	at clj_http.client$wrap_output_coercion$fn__2987.invoke(client.clj:438)
	at clj_http.client$wrap_exceptions$fn__2871.invoke(client.clj:189)
	at clj_http.client$wrap_accept$fn__3031.invoke(client.clj:565)
	at clj_http.client$wrap_accept_encoding$fn__3037.invoke(client.clj:579)
	at clj_http.client$wrap_content_type$fn__3026.invoke(client.clj:554)
	at clj_http.client$wrap_form_params$fn__3108.invoke(client.clj:726)
	at clj_http.client$wrap_nested_params$fn__3125.invoke(client.clj:755)
	at clj_http.client$wrap_method$fn__3078.invoke(client.clj:670)
	at clj_http.cookies$wrap_cookies$fn__1176.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__2061.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__3134.invoke(client.clj:771)
	at clj_http.client$post.doInvoke(client.clj:886)
	at clojure.lang.RestFn.invoke(RestFn.java:423)

**Comment by chihyangscience** [comment]
if I unizp the jar, I can see:  core$add_client_params_BANG_.class

this looks like in core-old namespace, I use Leiningen 2.4.3 on Java 1.7.0_67 Java HotSpot(TM) 64-Bit Server VM

**Comment by dakrone** [comment]
Hmm.. when I check out the `2.0.0` tag there is no `core_old.clj` file (see: https://github.com/dakrone/clj-http/tree/821e9a034ce7990ac8beebfa31f32ba8e53fea8f/src/clj_http ). Do you have some sort of unclean working tree?

**Comment by chihyangscience** [comment]
sorry, I am not using the build with master branch.
