### ISSUE TITLE
clj-http "3.6.1" not working with TLSv1.1 and TLSv1.2

### ISSUE THREAD

**Issue by chihyangscience** [dakrone/clj-http#382]
I use clj-http "3.6.1" to send https request a server only support > TLS1.1 version, but seems not working, anything I have to set before send requests?
```
20:25:05,031 INFO  [SoapUIProTestCaseRunner] Running SoapUI testcase [send standard email notification to contacts in one group_NE682]
20:25:05,032 INFO  [SoapUIProTestCaseRunner] running step [get group id by name]
20:25:05,173 ERROR [SoapUI] An error occurred [unable to find valid certification path to requested target], see error log for details
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:543)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at clj_http.core$request.invoke(core.clj:298)
	at clojure.lang.Var.invoke(Var.java:379)
	at clj_http.client$wrap_request_timing$fn__2195.invoke(client.clj:801)
	at clj_http.headers$wrap_header_map$fn__891.invoke(headers.clj:143)
	at clj_http.client$wrap_query_params$fn__2111.invoke(client.clj:624)
	at clj_http.client$wrap_basic_auth$fn__2118.invoke(client.clj:640)
	at clj_http.client$wrap_oauth$fn__2122.invoke(client.clj:650)
	at clj_http.client$wrap_user_info$fn__2127.invoke(client.clj:663)
	at clj_http.client$wrap_url$fn__2181.invoke(client.clj:767)
	at clj_http.client$wrap_redirects$fn__1939.invoke(client.clj:237)
	at clj_http.client$wrap_decompression$fn__1958.invoke(client.clj:309)
	at clj_http.client$wrap_input_coercion$fn__2050.invoke(client.clj:488)
	at clj_http.client$wrap_additional_header_parsing$fn__2071.invoke(client.clj:522)
	at clj_http.client$wrap_output_coercion$fn__2041.invoke(client.clj:438)
	at clj_http.client$wrap_exceptions$fn__1925.invoke(client.clj:189)
	at clj_http.client$wrap_accept$fn__2085.invoke(client.clj:565)
	at clj_http.client$wrap_accept_encoding$fn__2091.invoke(client.clj:579)
	at clj_http.client$wrap_content_type$fn__2080.invoke(client.clj:555)
	at clj_http.client$wrap_form_params$fn__2162.invoke(client.clj:726)
	at clj_http.client$wrap_nested_params$fn__2176.invoke(client.clj:756)
	at clj_http.client$wrap_method$fn__2132.invoke(client.clj:670)
	at clj_http.cookies$wrap_cookies$fn__174.invoke(cookies.clj:124)
	at clj_http.links$wrap_links$fn__1076.invoke(links.clj:51)
	at clj_http.client$wrap_unknown_host$fn__2185.invoke(client.clj:776)
	at clj_http.client$get.doInvoke(client.clj:879)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
```

**Comment by dakrone** [comment]
> anything I have to set before send requests?

There shouldn't be, is this an internet accessible server so I can try to reproduce this against it?

**Comment by prayagupd** [comment]
Probably similar issue as https://github.com/dakrone/clj-http/issues/388 which potentially can be fixed after installing cert to `$JAVA_HOME/jre/lib/security/` (using https://github.com/escline/InstallCert/blob/master/InstallCert.java).

Make sure connection can be made using `openssl` first.

**Comment by dakrone** [comment]
@chihyangscience can you verify that a connection to the server can be made with `openssl` first?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
