### ISSUE TITLE
NoClassDefFoundError Could not initialize class clj_http.client__init  java.lang.Class.forName0 (Class.java:-2)

### ISSUE THREAD

**Issue by shashank090789** [dakrone/clj-http#386]

**Comment by dakrone** [comment]
Could you provide the full stacktrace? where you are seeing this? What version of clj-http and clojure?

**Comment by rmcv** [comment]
I have similar issue with 3.7.0

 [clj-http "3.7.0"]
   [org.apache.httpcomponents/httpclient "4.5.3" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpcore "4.4.6" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpmime "4.5.3" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.3" :exclusions [[org.clojure/clojure]]]
     [riddley "0.1.12"]
   [slingshot "0.12.2" :exclusions [[org.clojure/clojure]]]

java.lang.ExceptionInInitializerError

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Class.java:348)

	at clojure.lang.RT.classForName(RT.java:2204)

	at clojure.lang.RT.classForName(RT.java:2213)

	at clojure.lang.RT.loadClassForName(RT.java:2232)

	at clojure.lang.RT.load(RT.java:450)

	at clojure.lang.RT.load(RT.java:426)

	at clojure.core$load$fn__6550.invoke(core.clj:6051)

	at clojure.core$load.invokeStatic(core.clj:6050)

	at clojure.core$load.doInvoke(core.clj:6034)

	at clojure.lang.RestFn.invoke(RestFn.java:408)

	at clojure.core$load_one.invokeStatic(core.clj:5853)

	at clojure.core$load_one.invoke(core.clj:5848)

	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)

	at clojure.core$load_lib.invokeStatic(core.clj:5892)

	at clojure.core$load_lib.doInvoke(core.clj:5873)

	at clojure.lang.RestFn.applyTo(RestFn.java:142)

	at clojure.core$apply.invokeStatic(core.clj:659)

	at clojure.core$load_libs.invokeStatic(core.clj:5930)

	at clojure.core$load_libs.doInvoke(core.clj:5914)

	at clojure.lang.RestFn.applyTo(RestFn.java:137)

	at clojure.core$apply.invokeStatic(core.clj:659)

	at clojure.core$require.invokeStatic(core.clj:5952)

	at clojure.core$require.doInvoke(core.clj:5952)

	at clojure.lang.RestFn.invoke(RestFn.java:805)

	at clj_http.client$loading__6436__auto____16646.invoke(client.clj:1)

	at clj_http.client__init.load(Unknown Source)

	at clj_http.client__init.<clinit>(Unknown Source)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Class.java:348)

	at clojure.lang.RT.classForName(RT.java:2204)

	at clojure.lang.RT.classForName(RT.java:2213)

	at clojure.lang.RT.loadClassForName(RT.java:2232)

	at clojure.lang.RT.load(RT.java:450)

	at clojure.lang.RT.load(RT.java:426)

	at clojure.core$load$fn__6550.invoke(core.clj:6051)

	at clojure.core$load.invokeStatic(core.clj:6050)

	at clojure.core$load.doInvoke(core.clj:6034)

	at clojure.lang.RestFn.invoke(RestFn.java:408)

	at clojure.core$load_one.invokeStatic(core.clj:5853)

	at clojure.core$load_one.invoke(core.clj:5848)

	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)

	at clojure.core$load_lib.invokeStatic(core.clj:5892)

	at clojure.core$load_lib.doInvoke(core.clj:5873)

	at clojure.lang.RestFn.applyTo(RestFn.java:142)

	at clojure.core$apply.invokeStatic(core.clj:659)

	at clojure.core$load_libs.invokeStatic(core.clj:5930)

	at clojure.core$load_libs.doInvoke(core.clj:5914)

	at clojure.lang.RestFn.applyTo(RestFn.java:137)

	at clojure.core$apply.invokeStatic(core.clj:659)

	at clojure.core$require.invokeStatic(core.clj:5952)

	at clojure.core$require.doInvoke(core.clj:5952)

	at clojure.lang.RestFn.invoke(RestFn.java:930)

**Comment by rymndhng** [comment]
@rmcv do you have more information about the Java & Clojure version used as well?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.
