### ISSUE TITLE
clj-http/get on https endpoint does not work with basic-auth

### ISSUE THREAD

**Issue by prayagupd** [dakrone/clj-http#388]
I am sending a GET request to my https endpoint, but clj-http fails with `SunCertPathBuilderException`

environments
------------------

```
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Same problem is with `[clj-http "3.5.0"]`, `[clj-http "3.6.0"]` or `[clj-http "3.6.1"]`, so probably my code is wrong.

```clj

(require '[clj-http.client :as http])

(http/get "https://some-endpoint/authentication/roleArns" {:headers {:Authorization "base64_hash"}})

SunCertPathBuilderException unable to find valid certification path to requested target  sun.security.provider.certpath.SunCertPathBuilder.build (SunCertPathBuilder.java:141)
```

Same problem with clj-http [`:basic-auth`](https://github.com/dakrone/clj-http#basic-auth)

```clj
(http/get "https://some-endpoint/authentication/roleArns" {:basic-auth "my_username:my_password"})

SunCertPathBuilderException unable to find valid certification path to requested target  sun.security.provider.certpath.SunCertPathBuilder.build (SunCertPathBuilder.java:141)
```

```clj

(http/get "https://some-endpoint/authentication/roleArns" {:basic-auth ["my_username" "my_password"]})

SunCertPathBuilderException unable to find valid certification path to requested target  sun.security.provider.certpath.SunCertPathBuilder.build (SunCertPathBuilder.java:141)

```

I think Im properly following the README - https://github.com/dakrone/clj-http#basic-auth, and **cURL** is working fine, 

```bash
curl -XGET  -H "Content-Type: application/json" -H "Authorization: Basic base64_hash" https://some-endpoint/authentication/roleArns
```

Update
--------

Actually https connection from java code is failing, as I see scala code is failing too, 

```scala
    val resourceIdentifier = "/authentication/resources"

    val connectionFlow: Flow[HttpRequest, HttpResponse, Future[Http.OutgoingConnection]] =
      Http().outgoingConnectionHttps("some-endpoint.net")

    Source.single(HttpRequest(uri = Uri(resourceIdentifier),
      headers = List(RawHeader("Authorization", "Basic base64_hash"))))
      .via(connectionFlow)
      .runWith(Sink.head)
      .andThen {
      case Success(response) => println("[INFO] " + response.status)
      case Failure(failure) => {
        failure.printStackTrace()
        println ("[ERROR] " + failure.getMessage)
      }
    }.andThen {
      case _ => system.terminate()
    }
```

error

```bash
trustStore is: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/security/cacerts
trustStore type is : jks
trustStore provider is : 
init truststore

....

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
	... 34 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
	... 40 more
```

**Comment by prayagupd** [comment]
Apparently java cacerts needed to be updated with cert for above endpoint. Used https://github.com/escline/InstallCert/blob/master/InstallCert.java.
