### ISSUE TITLE
java.lang.IllegalStateException: Illegal state ACTIVE when running integration tests

### ISSUE THREAD

**Issue by dakrone** [dakrone/clj-http#443]
When running the integration tests, this ERROR is currently logged:

```
[2018-03-24T21:40:15,344][ERROR][o.a.h.i.n.c.InternalHttpAsyncClient] I/O reactor terminated abnormally
java.lang.IllegalStateException: Illegal state ACTIVE
	at org.apache.http.util.Asserts.check(Asserts.java:46) ~[httpcore-4.4.9.jar:4.4.9]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:313) ~[httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194) ~[httpasyncclient-4.1.3.jar:4.1.3]
	at clj_http.conn_mgr.proxy$org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$ReuseableAsyncConnectionManager$fff3515b.execute(Unknown Source) ~[?:?]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.3.jar:4.1.3]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

It would be good to investigate what is causing this bad behavior.

**Comment by dakrone** [comment]
Here's an example test that causes the failure: `lein test :only clj-http.test.client-test/t-with-async-pool`
