### ISSUE TITLE
Send HTTP get , why java.io.EOFException: Unexpected end of ZLIB input stream ?

### ISSUE THREAD

**Issue by youkale** [dakrone/clj-http#509]
{:user-info nil,
 :use-header-maps-in-response? true,
 :body-type nil,
 :debug true,
 :headers
 {"Authorization" "bearer 88c9ebe96d15491992e0dc310c5162ea",
  "accept-encoding" "gzip, deflate"},
 :server-port nil,
 :url "https://pre.cloud.hecom.cn/oapi/v1/data/objects",
 :flatten-nested-keys (:query-params),
 :uri "/oapi/v1/data/objects",
 :server-name "pre.cloud.hecom.cn",
 :query-string "",
 :body nil,
 :scheme :https,
 :request-method :get}
HttpRequest:
{:config nil,
 :method "GET",
 :requestLine
 #object[org.apache.http.message.BasicRequestLine 0xd7bbf12 "GET https://pre.cloud.hecom.cn/oapi/v1/data/objects? HTTP/1.1"],
 :aborted false,
 :params
 #object[org.apache.http.params.BasicHttpParams 0x2272cbb0 "[parameters={}]"],
 :protocolVersion
 #object[org.apache.http.HttpVersion 0x5634a861 "HTTP/1.1"],
 :URI
 #object[java.net.URI 0x707ca986 "https://pre.cloud.hecom.cn/oapi/v1/data/objects?"],
 :class org.apache.http.client.methods.HttpGet,
 :allHeaders
 [#object[org.apache.http.message.BasicHeader 0x5e26f1ed "Connection: close"],
  #object[org.apache.http.message.BasicHeader 0x3becc950 "Authorization: bearer 88c9ebe96d15491992e0dc310c5162ea"],
  #object[org.apache.http.message.BasicHeader 0x6b9fdbc6 "accept-encoding: gzip, deflate"]]}
Exception in thread "main" java.io.EOFException: Unexpected end of ZLIB input stream
	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:70)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at clj_http.core.proxy$java.io.FilterInputStream$ff19274a.read(Unknown Source)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:183)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.Reader.read(Reader.java:229)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2537)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2516)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2493)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2441)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1084)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1110)
	at clj_http.util$force_string.invokeStatic(util.clj:92)
	at clj_http.util$force_string.invoke(util.clj:82)
	at clj_http.client$fn__2626.invokeStatic(client.clj:564)
	at clj_http.client$fn__2626.invoke(client.clj:562)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at clj_http.client$output_coercion_response.invokeStatic(client.clj:569)
	at clj_http.client$output_coercion_response.invoke(client.clj:566)
	at clj_http.client$wrap_output_coercion$fn__2634.invoke(client.clj:580)
	at clj_http.client$wrap_exceptions$fn__2481.invoke(client.clj:262)
	at clj_http.client$wrap_accept$fn__2687.invoke(client.clj:734)
	at clj_http.client$wrap_accept_encoding$fn__2694.invoke(client.clj:756)
	at clj_http.client$wrap_content_type$fn__2681.invoke(client.clj:717)
	at clj_http.client$wrap_form_params$fn__2780.invoke(client.clj:958)
	at clj_http.client$wrap_nested_params$fn__2801.invoke(client.clj:992)
	at clj_http.client$wrap_flatten_nested_params$fn__2810.invoke(client.clj:1016)
	at clj_http.client$wrap_method$fn__2748.invoke(client.clj:892)
	at clj_http.cookies$wrap_cookies$fn__1157.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__2284.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__2818.invoke(client.clj:1045)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1173)
	at clj_http.client$request_STAR_.invoke(client.clj:1166)
	at clj_http.client$get.invokeStatic(client.clj:1179)
	at clj_http.client$get.doInvoke(client.clj:1175)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at com.shudi.func.http$do_request.invokeStatic(http.clj:45)

**Comment by rymndhng** [comment]
First of all, your credentials are compromised now. I strongly advise you rotate your Bearer token because Github content is publicly available on the internet.

---

I suspect the server you're talking to doesn't handle gzip properly. I tested the same request using `curl` and it also encounters problems:

``` bash
> curl -v https://pre.cloud.hecom.cn/oapi/v1/data/objects -H"Authorization: Bearer YOUR_AUTH" -H"Accept-Encoding: gzip, deflate" | gunzip -
gunzip: (stdin): unexpected end of file
```

You can disable decompression by specifying two things. You need to disable it from being added in clj-http and you aslo need to disable it from the underlying Apache HTTPClient library.

``` clojure
(defn disable-decompression [^org.apache.http.impl.client.HttpClientBuilder builder request] 
  (.disableContentCompression builder))

(request {:headers {"Authorization" "Bearer YOUR_AUTH"},
          :url "https://pre.cloud.hecom.cn/oapi/v1/data/objects",
          :request-method :get
          :debug true

          ;; add these two options
          :decompress-body false
          :http-builder-fns [disable-decompression]
          })
```

**Comment by youkale** [comment]
token is rotated ,  thanks for your help and remind .
